name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to HF Space
        uses: huggingface/hub-action@v1   # <-- обычный дефис!
        with:
          repo-id: nimzuk/clodes          # <--- твой Space: owner/space_name
          token: ${{ secrets.HF_TOKEN }}
          path: .                         # что синкать (корень репо)
